### ISSUE TITLE
Pint design and implementation -  parent Issue

### ISSUE THREAD

**Issue by mohammadfawaz** [essential-contributions/pint#15]
### Opens

1. [ ] Program structure:
    1. #28: `constrain { }` block v.s. `constraint` statements.
    1. Decision variables. Do we need a separate block for these? (related: #27)
    1. Parameters. These are like constants but can be modified for each instantiation of a model. Kinda like environment variables.
    1. Local variables (these are variables defined inside functions and could represent parameters or decision variables).
1. [ ] #26: Dependencies and Imports.
    1. Following Rust is one option.
1. [ ] #32: Input data for parametrizable models. We could use a `toml` file here.
1. [ ] #25: State transition function statement: e.g. `u ~> v`.
1. [ ] #22: Native asset balance: e.g. `let bal = __eth_balance(EthAddress { .. })`. Chain-specific intrinsics.
1. [ ] #23: Contract calls: e.g. `var bal = EthContract { }.balanceOf( EthAddress { .. })`. How to _import_ interfaces of deployed contracts to be able to functions like `balanceOf`?
1. [ ] #24: How to handle conversions between "modelling types" such as `int` and external (Solidity?) types such as `uint256`.
1. [ ] #33: Print or output statements. 

## Implementation (+ some partial opens)

1. [ ] #18: Decide on a parser (Maybe using [Chumsky](https://github.com/zesterer/chumsky)?) to use and build a skeleton with at least the following:
    1. [ ] #29: Types:
        1. [ ] Basic types: `int`, `float`, `bool`. `str`.
        1. [ ] Aggregate type declarations: `struct { .. }`, `enum { .. }`.
        1. [ ] Aggregate type expressions.
    1. [ ] Literlas: decimals, floats, hex, strings.
    1. [ ] #27: Decision variables (`var`) v.s. parameters (`param`).
    1. [ ] Basic unary and binary expressions: `+`, `-`, `*`, `&&`, `||`, etc.
    1. [ ] Functions and function calls: function arguments can be decision variables or parameters.
    1. [ ] #31: `if` expressions.
    1. [ ] `solve` items (`satisfy`, `minimize`, `maximize`).
1. [ ] Toolchain:
    1. [ ] `pintc` executable and options: `solve`, `build`, `check` or `verify`, etc.
    1. [ ] #21: Package manager like `Cargo`, if needed: 
1. [ ] Backend:
    1. [ ] JSON representation of a program.
    1. [ ] Similarly to MiniZinc, target some default solver.

## Standard Library
This will be possible when we have enough of the language built to make building libraries useful.

## Testing

1. #19: Basic unit tests for the parser + CI.
1. #30: Basic testing infra
1. Basic tests once a backend with a solver is implemented.
    1. Check solutions.
    1. Check generated JSON representation.

## Examples

1. [ ] Complex but useful examples using the DSL.

## Future

1. [ ] Formatter: #20
3. [ ] Language Server, at least something basic to make the VSCode experience more ergonomic (syntax highlighting, etc.)

**Comment by mohammadfawaz** [comment]
This is mostly done... The rest of the core work is tracked in specific issues.
